// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djqqwniayufmwvshbaxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqcXF3bmlheXVmbXd2c2hiYXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODI2NTEsImV4cCI6MjA2OTQ1ODY1MX0.-aFxWzPbSv6L4gBYs2ZhaqonsByK3Ch7Dpj3jCA97Gg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});